import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  quickappSidebar: [
    'index',
    {
      type: 'category',
      label: '开发指南',
      items: [{type: 'autogenerated', dirName: 'guide'}],
    },
    {
      type: 'category',
      label: '组件',
      items: [{type: 'autogenerated', dirName: 'components'}],
    },
    {
      type: 'category',
      label: '接口',
      items: [{type: 'autogenerated', dirName: 'features'}],
    },
    {
      type: 'category',
      label: '工具链',
      items: [{type: 'autogenerated', dirName: 'tools'}],
    },
    'samples/index',
  ],
};

export default sidebars;
